name: Build-Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Lint
      run: |
        cargo install clippy && make lint
    - name: Run make file
      run: |
        make test code-style code-lint
